/// Flutter icons FamilleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FamilleIcons
///      fonts:
///       - asset: fonts/FamilleIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FamilleIcons {
  FamilleIcons._();

  static const _kFontFam = 'FamilleIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angledown = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleleft = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anglesmalldown = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appsadd = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmarkfilled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData childhead = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clip = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crosscircle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dart = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dicegame = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData following = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartfilled = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incognito = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listcheck = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuburger = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menudotsvertical = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modeportrait = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playingcards = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonecall = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData removeuser = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingssliders = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingbag = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signoutalt = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData treasurechest = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData useradd = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballot = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
